### PR TITLE
118-after-all-sign-up-methods-have-user-basic-info-in-firebase

### PR DESCRIPTION
**Pull request by softwarebyze**

### CODE REVIEW

**Comment by softwarebyze** [comment]
I'm getting an error on Android where it just gets stuck loading when trying to log in and says the client is offline. I checked the web browser in the emulator and it works fine.

image

**Comment by softwarebyze** [comment]
But I'm happy with how it's working on iOS. This video shows signing up a new user, saving details, location, and interests to Firebase, and then logging in and going straight to the home page.


https://github.com/softwarebyze/Places/assets/77241170/142eb3fc-3415-4375-9e1f-5921b912356e

**Comment by softwarebyze** [comment]
added loading to signup page

https://github.com/softwarebyze/Places/assets/77241170/9ee12b63-56f8-441d-a368-ea33c41d13fe

**Review by simonac2-gif — APPROVED** [review]

**Comment by softwarebyze** [comment]
> I'm getting an error on Android where it just gets stuck loading when trying to log in and says the client is offline. I checked the web browser in the emulator and it works fine.
> 
> image

This is the other error I get

image

**Pull request merged**
